### ISSUE TITLE
How does this compare to Tink?

### ISSUE THREAD

**Issue by garygreen** [mistic/static-fs#99]
From a basic understanding of the readme it sounds like this package shares similarities to [Tink](https://github.com/npm/tink) the main difference being that static-fs still installs everything but under one file, whereas Tink installs things on-demand when needed. Is this a fair comparison? Would the main work done with `static-fs` be deprecated when Tink is released in an upcoming npm release?

**Comment by mistic** [comment]
Hi @garygreen thanks for the question when stopping by this repo.The main problems we are trying to solve with the `static-fs` are listed here: https://github.com/elastic/kibana/issues/43357 and this is our experimental approach to solve them.

On Kibana we are shipping our node_modules into the distributable itself, which causes a number of problems (specially on windows). 

So the idea is to use the `static-fs` as a tool that would run during our distributable build, able to bundle a compilation of files in a single raw file volume (or a group of volumes) and then patches the node and the app we are shipping to be able to read from those volumes (the static-fs).

That way we can still ship our distributable as we want, and lower the final file count.
